id: P010503
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:53:06.254508
source_metadata:
  id: bdr:W1KG982
  title: གསོ་རིག་དཔྱད་རྩོམ་ཀུནྡ་དགྱེས་པའི་ཟླ་ཟེར་
  author: ''
  volumes:
    165e8e1721974b17b1ad9e512fc5958c:
      image_group_id: I1KG1127
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
