id: I669AAA01
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:52:23+00:00'
last_modified: '2022-06-08T14:04:42.532657+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG982
  title: གསོ་རིག་དཔྱད་རྩོམ་ཀུནྡ་དགྱེས་པའི་ཟླ་ཟེར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3786':
      image_group_id: I1KG1127
      title: ''
      total_pages: 274
      order: 1
      base_file: 3786.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
